[src]
exclude = ["**/*arcpy*"]

[environment]
python-version = "3.12"

[rules]
unsupported-operator = "error"
invalid-return-type = "error"
unresolved-import = "warn"
invalid-assignment = "error"
invalid-argument-type = "warn"
non-subscriptable = "error"
not-iterable = "error"
no-matching-overload = "warn"
invalid-parameter-default = "error"
possibly-missing-attribute = "warn"
redundant-cast = "error"
unresolved-reference = "warn"
unresolved-attribute = "warn"
unresolved-global = "warn"
